rocketmq:
  producer:
    access-key: AK
    secret-key: SK
    group: test
    send-message-timeout: 300000

  name-server: localhost:9876
  consumer:
    access-key: AK
    secret-key: SK
    group: test
server:
  port: 8082

